---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-env-config
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.app.labels.app }}
data:
  KC_DB_PASSWORD: {{ .Values.app.db.password }}
  KC_DB_URL_DATABASE: {{ .Values.app.db.name }}
  KC_DB_URL_HOST: {{ .Values.app.db.host }}
  KC_DB_USERNAME: {{ .Values.app.db.username }}
  KC_DB: {{ .Values.app.db.type }}
  KC_HEALTH_ENABLED: "true"
  KC_HOSTNAME_ADMIN_URL: "https://{{ .Values.app.hostname }}:30443/"
  KC_HOSTNAME_URL: "https://{{ .Values.app.hostname }}:30443/"
  KC_HTTP_ENABLED: "true"
  KC_HTTP_RELATIVE_PATH: /
  KC_HTTPS_CERTIFICATE_FILE: $${kc.home.dir}/conf/tls/tls.crt
  KC_HTTPS_CERTIFICATE_KEY_FILE: $${kc.home.dir}/conf/tls/tls.key
  KC_METRICS_ENABLED: "true"
  KEYCLOAK_ADMIN: admin
  jgroups.dns.query: keycloak
  PROXY_ADDRESS_FORWARDING: "true"
