---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.app.labels.app }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.app.labels.app }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: {{ .Values.app.labels.app }}
    spec:
      containers:
        - name: {{ .Release.Name }}
          image: quay.io/keycloak/keycloak:26.0.7
          args: ["start", "--cache-stack=kubernetes", "--hostname", "{{ .Values.app.hostname }}"]
          env:
            - name: KEYCLOAK_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-pwd
                  key: KEYCLOAK_ADMIN_PASSWORD
          envFrom:
            - configMapRef:
                name: {{ .Release.Name }}-env-config
          ports:
            - name: jgroups
              containerPort: 7600
            - name: http
              containerPort: 8080
            - name: https
              containerPort: 8443
          livenessProbe:
            httpGet:
              path: /realms/master
              port: 8080
              scheme: HTTP
            periodSeconds: 15
          readinessProbe:
            httpGet:
              path: /realms/master
              port: 8080
              scheme: HTTP
            periodSeconds: 15
          resources:
            requests:
              cpu: 100m
              memory: 500Mi
            limits:
              memory: 600Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            runAsNonRoot: true
            runAsUser: 1000
            seccompProfile:
              type: RuntimeDefault
          startupProbe:
            failureThreshold: 20
            httpGet:
              path: /realms/master
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 5
          volumeMounts:
            - name: tls-crt
              mountPath: /opt/keycloak/conf/tls
      serviceAccount: {{ .Release.Name }}
      volumes:
        - name: tls-crt
          secret:
            secretName: {{ .Values.app.hostname }}-tls
