# Default values for monitoring.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

prometheus:
  cert:
    dnsNames:
      - prometheus.example.com
    # issuerName: letsencrypt-prod | letsencrypt-staging
    issuerName: letsencrypt-prod
    orgs:
      - example.com

  exporters:
    node:
      enabled: false

  hostname: prometheus.example.com

blackbox:
  enabled: false

netload:
  enabled: false

node-exporter:
  enabled: false

snmp:
  enabled: false
