# Default values for monitoring.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

prometheus:
  dataVolume:
    size: 500Mi
    # type: emptydir (default) | pvc_nfs
    type: emptydir

  cert:
    dnsNames:
      - prometheus.example.com
    # issuerName: letsencrypt-prod | letsencrypt-staging
    issuerName: letsencrypt-prod
    orgs:
      - example.com

  hostname: prometheus.example.com

  pv:
    nfs:
      path: /data/prometheus
      server: 192.168.1.1
    size: 5Gi
    storageClassName: slow

blackbox:
  enabled: false

  targets: []

node_exporter:
  enabled: true

snmp:
  enabled: false
