---
# Default values for monitoring.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

prometheus:
  dataVolume:
    size: 500Mi
    # type: emptydir (default) | pvc_nfs
    type: emptydir

  cert:
    dnsNames:
      - prometheus.example.com
    # issuerName: letsencrypt-prod | letsencrypt-staging
    issuerName: letsencrypt-staging
    orgs:
      - example.com

  hostname: prometheus.example.com

  pv:
    nfs:
      path: /data/prometheus
      server: 192.168.1.1
    size: 5Gi
    storageClassName: slow

# blackbox-exporter
blackbox:
  enabled: false

  # Example targets
  targets:
    - example.com

# docker metrics
docker:
  enabled: false

  # Example static configs
  static_configs:
    - labels:
        instance: docker-host
      targets:
        - 192.168.1.1:9323

# mysqld-exporter
mysqld:
  enabled: false

  # Example static configs
  static_configs:
    - labels:
        instance: mysql-host
      targets:
        - 192.168.1.1:9104

# node-exporter
node:
  enabled: false

  # Example static configs
  static_config:
    - labels:
        instance: linux-host
      targets:
        - 192.168.1.1:9100

# node-exporter for kubernetes
node_exporter:
  enabled: true

# snmp-exporter
snmp:
  enabled: false
