---
# Default values for monitoring.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

prometheus:
  cert:
    dnsNames:
      - prometheus.example.com
    # issuerName: letsencrypt-prod | letsencrypt-staging
    issuerName: letsencrypt-staging
    orgs:
      - example.com

  dataVolume:
    size: 500Mi
    type: emptydir

  hostname: prometheus.example.com

  nodePort: 30090

  pvc:
    enabled: false

  remoteWrite:
    enabled: false

    # https://grafana.com/docs/alloy/latest/reference/components/prometheus/prometheus.remote_write/
    endpoints: []

  # scrape_configs
  scrape:
    blackbox: false
    docker: false
    kubernetes: false
    kubeStateMetrics: false
    mysqld: false
    node: false
    nodeExporter: false

  pv:
    nfs:
      path: /data/prometheus
      server: 192.168.1.1
    size: 5Gi
    storageClassName: slow

# blackbox-exporter
blackbox:
  enabled: false

  # List of domain names
  targets: []

# docker metrics
docker:
  enabled: false

  # Example static configs
  static_configs:
    - labels:
        instance: docker-host
      targets:
        - 192.168.1.1:9323

# mysqld-exporter
mysqld:
  enabled: false

  # Example static configs
  static_configs:
    - labels:
        instance: mysql-host
      targets:
        - 192.168.1.1:9104

# node-exporter
node:
  enabled: false

  # Example static configs
  static_config:
    - labels:
        instance: linux-host
      targets:
        - 192.168.1.1:9100

# node-exporter for kubernetes
nodeExporter:
  enabled: false

# snmp-exporter
snmp:
  enabled: false
