---
apiVersion: v1
kind: Service
metadata:
  name: node-exporter
  namespace: {{ .Release.Namespace }}
  labels:
    app: node-exporter
    release: {{ .Release.Name }}
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/port: '9100'
spec:
  selector:
    app: node-exporter
  ports:
    - name: node-exporter
      port: 9100
      targetPort: 9100
