---
generatorOptions:
  disableNameSuffixHash: true
  labels:
    name: grafana-config
configMapGenerator:
  - name: grafana-config
    namespace: monitoring
    files:
      - grafana.ini
      - provider.yml
