---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-config
  namespace: monitoring
  labels:
    app: grafana
data:
  custom.ini: |
    # Grafana custom configuration
    # Defaults: https://github.com/grafana/grafana/tree/main/conf

    [server]
    # Protocol (http, https, h2, socket)
    protocol = https
    # The full public facing url you use in browser, used for redirects and emails
    # If you use reverse proxy and sub path specify full url (with sub path)
    root_url = https://grafana.k8s.reiciunas.dev:30030/

    # https certs & key file
    cert_file = /etc/grafana/tls/tls.crt
    cert_key = /etc/grafana/tls/tls.key

    [database]
    type = postgres
    host = postgres.system.svc.cluster.local
    name = grafana
    user = grafana
    password = grafana

    [smtp]
    enabled = true
    host = 192.168.68.2:25

    from_address = grafana@reiciunas.dev
    from_name = Grafana

    [auth.generic_oauth]
    enabled = true
    name = KeyCloak SSO
    allow_sign_up = true
    client_id = grafana
    client_secret = admsYcOJqITybDYAWOJAHp1g91uaP9mp
    scopes = openid email profile offline_access roles
    email_attribute_path = email
    login_attribute_path = username
    name_attribute_path = full_name
    auth_url = https://keycloak.k8s.reiciunas.dev:30443/realms/reiciunas/protocol/openid-connect/auth
    token_url = https://keycloak.k8s.reiciunas.dev:30443/realms/reiciunas/protocol/openid-connect/token
    api_url = https://keycloak.k8s.reiciunas.dev:30443/realms/reiciunas/protocol/openid-connect/userinfo
    role_attribute_path = contains(roles[*], 'admin') && 'Admin' || contains(roles[*], 'editor') && 'Editor' || 'Viewer'
    tls_skip_verify_insecure = true

  provider.yml: |
    ---
    apiVersion: 1

    providers:
      - name: dashboards
        orgId: 1
        type: file
        disableDeletion: false
        updateIntervalSeconds: 30
        allowUiUpdates: true
        options:
          path: /etc/dashboards
          foldersFromFilesStructure: true

  prometheus.yml: |
    ---
    apiVersion: 1
    datasources:
      - name: prometheus
        type: prometheus
        orgId: 1
        updateIntervalSeconds: 30
        url: https://prometheus.k8s.reiciunas.dev:30090
