---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: monitoring
  labels:
    app: grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      securityContext:
        fsGroup: 472
        supplementalGroups:
          - 0
      containers:
        - name: grafana
          image: grafana/grafana:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: GF_PATHS_CONFIG
              value: /etc/grafana/custom.ini
          ports:
            - containerPort: 3000
          livenessProbe:
            httpGet:
              path: /robots.txt
              port: 3000
              scheme: HTTPS
            periodSeconds: 15
          readinessProbe:
            httpGet:
              path: /robots.txt
              port: 3000
              scheme: HTTPS
            periodSeconds: 15
          startupProbe:
            failureThreshold: 20
            httpGet:
              path: /robots.txt
              port: 3000
              scheme: HTTPS
            initialDelaySeconds: 10
            periodSeconds: 5
          resources:
            requests:
              cpu: 20m
              memory: 110Mi
            limits:
              memory: 110Mi
          volumeMounts:
            - name: config-volume
              mountPath: /etc/grafana/custom.ini
              subPath: custom.ini
            - name: config-volume
              mountPath: /etc/grafana/provisioning/datasources/prometheus.yml
              subPath: prometheus.yml
            - name: config-volume
              mountPath: /etc/grafana/provisioning/dashboards/provider.yml
              subPath: provider.yml
            - name: dashboards
              mountPath: /etc/dashboards
            - name: tls-crt
              mountPath: /etc/grafana/tls
        - name: sidecar-dashboards
          image: kiwigrid/k8s-sidecar
          env:
            - name: LABEL
              value: grafana_dashboard
            - name: FOLDER
              value: /etc/dashboards
          resources:
            requests:
              cpu: 10m
              memory: 100Mi
            limits:
              memory: 100Mi
          volumeMounts:
            - name: dashboards
              mountPath: /etc/dashboards
      serviceAccount: grafana
      volumes:
        - name: config-volume
          configMap:
            name: grafana-config
        - name: dashboards
          emptyDir: {}
        - name: tls-crt
          secret:
            secretName: grafana.k8s.reiciunas.dev
