---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-apps-to-{{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  ingress:
    - from:
        - namespaceSelector:
            matchExpressions:
              - key: kubernetes.io/metadata.name
                operator: In
                values:
                  # - monitoring
                  - {{ .Release.Namespace }}
      ports:
        - protocol: TCP
          port: 5432
  podSelector:
    matchLabels:
      app: postgres
  policyTypes:
    - Ingress
