---
{{- if eq .Values.postgres.dataVolume.type "pvc_nfs" }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.postgres.dataVolume.size }}
  storageClassName: {{ .Values.postgres.pvc.nfs.path.storageClassName }}
  volumeMode: Filesystem
{{- end }}
