---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: {{ .Release.Namespace }}
  labels:
    app: postgres
    release: {{ .Release.Name }}
spec:
  selector:
    app: postgres
  ports:
    - port: 5432
