# Default values for keycloak.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

keycloak:
  db:
    host: postgres
    name: keycloak
    password: keycloak
    type: postgres
    username: keycloak

  cert:
    dnsNames:
      - keycloak.example.com
    # issuerName: letsencrypt-prod | letsencrypt-staging
    issuerName: letsencrypt-staging
    orgs:
      - example.com

  hostname: keycloak.example.com
