---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: {{ .Release.Name }}
          image: postgres
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-pwd
                  key: POSTGRES_PASSWORD
          envFrom:
            - configMapRef:
                name: {{ .Release.Name }}-env-config
          ports:
            - containerPort: 5432
          livenessProbe:
            exec:
              command: ["pg_isready", "-U", "postgres"]
            periodSeconds: 15
          readinessProbe:
            exec:
              command: ["pg_isready", "-U", "postgres"]
            periodSeconds: 15
          resources:
            requests:
              cpu: 20m
              memory: 100Mi
            limits:
              memory: 200Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            runAsNonRoot: true
            runAsUser: 1000
            seccompProfile:
              type: RuntimeDefault
          startupProbe:
            failureThreshold: 10
            exec:
              command: ["pg_isready", "-U", "postgres"]
            initialDelaySeconds: 10
            periodSeconds: 5
          volumeMounts:
            - name: data-volume
              mountPath: /var/lib/postgresql/data
            - name: init-db
              mountPath: /docker-entrypoint-initdb.d
      securityContext:
        fsGroup: 26
      serviceAccount: {{ .Release.Name }}
      volumes:
        - name: data-volume
          {{- if eq .Values.app.dataVolume.type "pvc_nfs" }}
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-pvc
          {{- else }}
          emptyDir:
            sizeLimit: {{ .Values.app.dataVolume.size }}
          {{- end }}
        - name: init-db
          configMap:
            name: {{ .Release.Name }}-db-config
            defaultMode: 0555
