---
{{- if eq .Values.app.dataVolume.type "pvc_nfs" }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-pvc
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.app.dataVolume.size }}
  storageClassName: {{ .Values.app.pvc.nfs.path.storageClassName }}
  volumeMode: Filesystem
{{- end }}
