---
# basic_auth_users:
#   prometheus: sha

http_server_config:
  http2: true

tls_server_config:
  cert_file: /etc/prometheus/tls/tls.crt
  key_file: /etc/prometheus/tls/tls.key
  min_version: TLS12
