---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: {{ .Release.Namespace }}
  labels:
    app: grafana
    release: {{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: grafana
          image: grafana/grafana:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: GF_PATHS_CONFIG
              value: /etc/grafana/custom.ini
          ports:
            - containerPort: 3000
          livenessProbe:
            httpGet:
              path: /robots.txt
              port: 3000
              scheme: HTTPS
            periodSeconds: 15
          readinessProbe:
            httpGet:
              path: /robots.txt
              port: 3000
              scheme: HTTPS
            periodSeconds: 15
          resources:
            limits:
              memory: 110Mi
            requests:
              cpu: 20m
              memory: 110Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            runAsNonRoot: true
            runAsUser: 1000
            seccompProfile:
              type: RuntimeDefault
          startupProbe:
            failureThreshold: 20
            httpGet:
              path: /robots.txt
              port: 3000
              scheme: HTTPS
            initialDelaySeconds: 10
            periodSeconds: 5
          volumeMounts:
            - name: config-volume
              mountPath: /etc/grafana/custom.ini
              subPath: custom.ini
            {{- if .Values.grafana.dataSources.prometheus.enabled }}
            - name: config-volume
              mountPath: /etc/grafana/provisioning/datasources/prometheus.yml
              subPath: prometheus.yml
            {{- end }}
            {{- if .Values.grafana.providers.dashboards.enabled }}
            - name: config-volume
              mountPath: /etc/grafana/provisioning/dashboards/provider.yml
              subPath: provider.yml
            - name: dashboards
              mountPath: /etc/dashboards
            {{- end }}
            - name: tls-crt
              mountPath: /etc/grafana/tls
        {{- if .Values.grafana.providers.dashboards.enabled }}
        - name: sidecar-dashboards
          image: kiwigrid/k8s-sidecar
          env:
            - name: LABEL
              value: grafana_dashboard
            - name: FOLDER
              value: /etc/dashboards
          resources:
            limits:
              memory: 100Mi
            requests:
              cpu: 10m
              memory: 100Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            runAsNonRoot: true
            runAsUser: 1000
            seccompProfile:
              type: RuntimeDefault
          volumeMounts:
            - name: dashboards
              mountPath: /etc/dashboards
        {{- end }}
      securityContext:
        fsGroup: 472
        supplementalGroups:
          - 0
      serviceAccount: grafana
      volumes:
        - name: config-volume
          configMap:
            name: grafana-config
        - name: dashboards
          emptyDir: {}
        - name: tls-crt
          secret:
            secretName: {{ .Values.grafana.hostname }}-tls
