---
apiVersion: v1
kind: Service
metadata:
  name: snmp
  namespace: {{ .Release.Namespace }}
  labels:
    app: snmp
    release: {{ .Release.Name }}
spec:
  selector:
    app: snmp
  ports:
    - name: snmp
      port: 9116
      targetPort: 9116
