# Default values for grafana.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

grafana:

  cert:
    dnsNames:
      - grafana.example.com
    # issuerName: letsencrypt-prod | letsencrypt-staging
    issuerName: letsencrypt-staging
    orgs:
      - example.com

  hostname: grafana.example.com
