---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: keycloak.k8s.reiciunas.dev
  namespace: system
spec:
  dnsNames:
    - keycloak.k8s.reiciunas.dev
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-prod
  secretName: keycloak.k8s.reiciunas.dev
  subject:
    organizations:
      - reiciunas.dev
  usages:
    - client auth
    - server auth
