---
apiVersion: v1
kind: ConfigMap
metadata:
  name: keycloak-config
  namespace: system
  labels:
    app: keycloak
data:
  keycloak.conf: |-
    db=postgres
    db-username=keycloak
    db-password=keycloak
    db-url-host=postgres
    health-enabled=true
    metrics-enabled=true
    https-certificate-file=${kc.home.dir}/conf/tls/tls.crt
    https-certificate-key-file=${kc.home.dir}/conf/tls/tls.key
    # proxy=reencrypt
    # spi-sticky-session-encoder-infinispan-should-attach-route=false
    # hostname=keycloak.k8s.reiciunas.dev

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: keycloak-env-config
  namespace: system
  labels:
    app: keycloak
data:
  KEYCLOAK_ADMIN: admin
  KC_PROXY: edge
