---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  namespace: system
  labels:
    app: keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
        - name: keycloak
          image: quay.io/keycloak/keycloak:24.0.2
          args: ["start", "--cache-stack=kubernetes"]
          env:
            - name: KC_DB
              value: "postgres"
            - name: KC_DB_PASSWORD
              value: "keycloak"
            - name: KC_DB_USERNAME
              value: "keycloak"
            - name: KC_DB_URL_DATABASE
              value: keycloak
            - name: KC_DB_URL_HOST
              value: postgres
            - name: KC_HEALTH_ENABLED
              value: "true"
            - name: KC_METRICS_ENABLED
              value: "true"
            - name: KC_HOSTNAME_ADMIN_URL
              value: "https://keycloak.k8s.reiciunas.dev:30443/"
            - name: KC_HOSTNAME_URL
              value: "https://keycloak.k8s.reiciunas.dev:30443/"
            - name: KC_HTTP_ENABLED
              value: "true"
            - name: KC_HTTP_RELATIVE_PATH
              value: /
            - name: KC_HTTPS_CERTIFICATE_FILE
              value: $${kc.home.dir}/conf/tls/tls.crt
            - name: KC_HTTPS_CERTIFICATE_KEY_FILE
              value: $${kc.home.dir}/conf/tls/tls.key
            - name: KEYCLOAK_ADMIN
              value: admin
            - name: KEYCLOAK_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: keycloak-secret
                  key: KEYCLOAK_ADMIN_PASSWORD
            - name: jgroups.dns.query
              value: keycloak
            - name: PROXY_ADDRESS_FORWARDING
              value: "true"
          ports:
            - name: jgroups
              containerPort: 7600
            - name: http
              containerPort: 8080
            - name: https
              containerPort: 8443
          livenessProbe:
            httpGet:
              path: /realms/master
              port: 8080
              scheme: HTTP
            periodSeconds: 15
          readinessProbe:
            httpGet:
              path: /realms/master
              port: 8080
              scheme: HTTP
            periodSeconds: 15
          startupProbe:
            failureThreshold: 20
            httpGet:
              path: /realms/master
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 5
          resources:
            requests:
              cpu: 100m
              memory: 500Mi
            limits:
              memory: 600Mi
          volumeMounts:
            - name: tls-crt
              mountPath: /opt/keycloak/conf/tls
      serviceAccount: keycloak
      volumes:
        - name: tls-crt
          secret:
            secretName: keycloak.k8s.reiciunas.dev
