{
 "title": "Overview",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data source", "query": "prometheus" },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values({job=\"node\"},instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "CPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(sum(irate(node_cpu_seconds_total{mode!=\"idle\", instance=~\"$instance\"} [$__rate_interval])) by (instance)) / sum(irate(node_cpu_seconds_total{instance=~\"$instance\"}[$__rate_interval])) by (instance)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "node_memory_MemFree_bytes{instance=~\"$instance\"} / node_memory_MemTotal_bytes{instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Temperatures",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "avg(node_hwmon_temp_celsius{instance=~\"$instance\"} > 0) by (instance, sensor, chip)",
     "legendFormat": "{{instance}}: {{sensor}}"
    },
    {
     "expr": "smartmon_temperature_celsius_value{instance=~\"$instance\"}",
     "legendFormat": "{{instance}}: {{disk}}"
    }
   ]
  },
  {
   "title": "CPU Load",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "node_load1{instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "node_load5{instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "node_load15{instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Network Bytes: Rx/Tx",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(irate(node_network_receive_bytes_total{instance=~\"$instance\"}[$__rate_interval])) by (instance)",
     "legendFormat": "__auto"
    },
    {
     "expr": "-sum(irate(node_network_transmit_bytes_total{instance=~\"$instance\"}[$__rate_interval])) by (instance)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Alerts", "type": "alertlist", "gridPos": { "h": 8, "w": 8, "x": 16, "y": 8 } },
  {
   "title": "Disk Usage",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 8, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg((node_filesystem_size_bytes{instance=~\"$instance\"} - node_filesystem_free_bytes{instance=~\"$instance\"}) / node_filesystem_size_bytes{instance=~\"$instance\"}) by (instance, device)",
     "legendFormat": "{{instance}}: {{device}}"
    }
   ]
  },
  {
   "title": "Disk Bytes: Rx / Tx",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 8, "x": 8, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(irate(node_disk_read_bytes_total{instance=~\"$instance\"}[$__rate_interval])) by (instance, device)",
     "legendFormat": "{{instance}}: {{device}}"
    },
    {
     "expr": "-sum(irate(node_disk_written_bytes_total{instance=~\"$instance\"}[$__rate_interval])) by (instance, device)",
     "legendFormat": "{{instance}}: {{device}}"
    }
   ]
  },
  {
   "title": "Status",
   "type": "state-timeline",
   "gridPos": { "h": 12, "w": 8, "x": 16, "y": 16 },
   "targets": [
    {
     "expr": "sum(up{instance=~\"$instance\"}) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}