---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: blackbox
  namespace: {{ .Release.Namespace }}
  labels:
    app: blackbox
    release: {{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blackbox
  template:
    metadata:
      labels:
        app: blackbox
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: blackbox
          image: prom/blackbox-exporter
          ports:
            - containerPort: 9115
          livenessProbe:
            httpGet:
              path: /
              port: 9115
              scheme: HTTP
            periodSeconds: 15
          readinessProbe:
            httpGet:
              path: /
              port: 9115
              scheme: HTTP
            periodSeconds: 15
          resources:
            limits:
              memory: 100Mi
            requests:
              cpu: 10m
              memory: 100Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            runAsNonRoot: true
            runAsUser: 1000
            seccompProfile:
              type: RuntimeDefault
          startupProbe:
            failureThreshold: 20
            httpGet:
              path: /
              port: 9115
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 5
          volumeMounts:
            - name: config-volume
              mountPath: /etc/blackbox_exporter
      serviceAccount: blackbox
      volumes:
        - name: config-volume
          configMap:
            name: blackbox-config
