---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-ingress-to-blackbox
  namespace: {{ .Release.Namespace }}
  labels:
    app: blackbox
    release: {{ .Release.Name }}
spec:
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: prometheus
      ports:
        - protocol: TCP
          port: 9115
  podSelector:
    matchLabels:
      app: blackbox
  policyTypes:
    - Ingress
