---
apiVersion: v1
kind: Service
metadata:
  name: blackbox
  namespace: {{ .Release.Namespace }}
  labels:
    app: blackbox
    release: {{ .Release.Name }}
spec:
  selector:
    app: blackbox
  ports:
    - name: blackbox
      port: 9115
      targetPort: 9115
