# Default values for postgres.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

postgres:
  dataVolume:
    size: 200Mi
    # type: emptydir (default) | pvc_nfs
    type: emptydir

  dbs:
    - name: default
      password: default
      user: default

  labels:
    app: postgres

  pv:
    nfs:
      path: /data/postgres
      server: 192.168.1.1
    size: 10Gi
    storageClassName: slow
