---
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: {{ .Release.Namespace }}
  labels:
    app: prometheus
data:
  prometheus.yml: |-
    ---
    global:
      scrape_interval: 15s
      evaluation_interval: 15s

    # Alertmanager configuration
    alerting:
      alertmanagers:
        - static_configs:
            - targets:
                - "alertmanager.{{ .Release.Namespace }}.svc:9093"

    scrape_configs:

      - job_name: wcac

        scheme: http

        static_configs:
          - targets:
              - 192.168.68.32:30800
