---
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: {{ .Release.Namespace }}
  labels:
    app: prometheus
data:
  prometheus.yml: |-
    ---
    global:
      scrape_interval: 15s
      evaluation_interval: 15s

    # Alertmanager configuration
    alerting:
      alertmanagers:
        - static_configs:
            - targets:
                - "alertmanager.monitoring.svc:9093"

    scrape_configs:

      - job_name: blackbox
        metrics_path: /probe
        params:
          module:
            - http_2xx

        relabel_configs:
          - source_labels:
              - __address__
            target_label: __param_target

          - source_labels:
              - __param_target
            target_label: instance

          - replacement: blackbox.monitoring.svc.cluster.local:9115
            target_label: __address__

        static_configs:
          - targets:
              - reiciunas.dev
              - rubicbit.com
              - scoachingtherapy.com

      - job_name: docker

        static_configs:
          - labels:
              instance: store
            targets:
              - 192.168.68.3:9323

      - job_name: mysqld

        static_configs:
          - labels:
              instance: aws-mysql01
            targets:
              - 10.16.0.130:9104

      - job_name: node

        static_configs:
          - labels:
              instance: aws-mysql01
            targets:
              - 10.16.0.130:9100

          - labels:
              instance: aws-vpn01
            targets:
              - 10.16.4.83:9100

          - labels:
              instance: aws-web01
            targets:
              - 10.16.4.122:9100

          - labels:
              instance: fh01
            targets:
              - 100.85.71.13:9100

          - labels:
              instance: store
            targets:
              - 192.168.68.3:9100

      - job_name: wcac

        scheme: http

        static_configs:
          - targets:
              - 192.168.68.32:30800
