---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-ingress-to-{{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: prometheus
    release: {{ .Release.Name }}
spec:
  ingress:
    - ports:
        - protocol: TCP
          port: 9090
  podSelector:
    matchLabels:
      app: prometheus
  policyTypes:
    - Ingress
