---
{{- if .Values.prometheus.pv.enabled }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus-nfs-pv
  labels:
    type: nfs
spec:
  accessModes:
  {{ .Values.prometheus.pv.accessModes | toYaml | indent 2 }}
  capacity:
    storage: {{ .Values.prometheus.pv.capacity }}
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: {{ .Values.prometheus.pv.path }}
    server: {{ .Values.prometheus.pv.server }}
  persistentVolumeReclaimPolicy: Delete
  storageClassName: nfs
  volumeMode: Filesystem
{{- end }}
