---
{{- if .Values.prometheus.pvc.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-pvc
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.prometheus.dataVolume.size }}
  storageClassName: {{ .Values.prometheus.pvc.nfs.path.storageClassName }}
  volumeMode: Filesystem
{{- end }}
