---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-db-config
  # namespace: system
  labels:
    app: postgres
data:
  00-gitlab.sql: |-
    CREATE USER gitlab WITH SUPERUSER PASSWORD 'gitlab';
    CREATE DATABASE gitlab;
    GRANT ALL PRIVILEGES ON DATABASE gitlab TO gitlab;
  00-keycloak.sql: |-
    CREATE USER keycloak WITH SUPERUSER PASSWORD 'keycloak';
    CREATE DATABASE keycloak;
    GRANT ALL PRIVILEGES ON DATABASE keycloak TO keycloak;

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-env-config
  # namespace: system
  labels:
    app: postgres
data:
  PGDATA: /var/lib/postgresql/data/pgdata
  POSTGRES_DB: psql
  POSTGRES_USER: postgres
