---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: system
  labels:
    app: postgres
data:
  PGDATA: /var/lib/postgresql/data/pgdata
  POSTGRES_DB: psql
  POSTGRES_USER: postgres
