---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  # namespace: system
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: slow
  volumeMode: Filesystem
